#!/bin/bash

SERIAL_PORT=/dev/ttyACM0

REFLASH_EEPROM=true

make "handwired/dactyl_manuform/4x6:default"

# Should be able to omit after first flash?
read  -n 1 -p "Connect left hand and reset" x
if [[ $REFLASH_EEPROM ]] ; then
    sudo avrdude -p m32u4 -P $SERIAL_PORT -c avr109 -U eeprom:w:quantum/split_common/eeprom-lefthand.eep
    sleep 1
    read  -n 1 -p "Reset again" x
fi
sudo avrdude -p m32u4 -P $SERIAL_PORT -c avr109 -U flash:w:handwired_dactyl_manuform_4x6_default.hex

read  -n 1 -p "Connect right hand and reset" x
if [[ $REFLASH_EEPROM ]] ; then
    sudo avrdude -p m32u4 -P $SERIAL_PORT /dev/ttyACM0 -c avr109 -U eeprom:w:quantum/split_common/eeprom-righthand.eep
    sleep 1
    read  -n 1 -p "Reset again" x
fi
sudo avrdude -p m32u4 -P $SERIAL_PORT -c avr109 -U flash:w:handwired_dactyl_manuform_4x6_default.hex
