#!/bin/bash

SERIAL_PORT=/dev/ttyACM0

#REFLASH_EEPROM=true
REFLASH_EEPROM=false

make "handwired/dactyl_manuform/4x6:default" || exit 1

# Should be able to omit after first flash?
#read -r -n 1 -p "Connect left hand and reset" x
read -r -p "Connect left hand, reset, then hit enter" x
if $REFLASH_EEPROM ; then
    sudo avrdude -p m32u4 -P $SERIAL_PORT -c avr109 -U eeprom:w:quantum/split_common/eeprom-lefthand.eep || exit 2
    sleep 1
    read -r -p "Reset again" x
fi
sudo avrdude -p m32u4 -P $SERIAL_PORT -c avr109 -U flash:w:handwired_dactyl_manuform_4x6_default.hex || exit 3

read -r -p "Connect right hand, reset, then hit enter" x
if $REFLASH_EEPROM ; then
    sudo avrdude -p m32u4 -P $SERIAL_PORT /dev/ttyACM0 -c avr109 -U eeprom:w:quantum/split_common/eeprom-righthand.eep || exit 4
    sleep 1
    read -r -p "Reset again" x
fi
sudo avrdude -p m32u4 -P $SERIAL_PORT -c avr109 -U flash:w:handwired_dactyl_manuform_4x6_default.hex || exit 5
